### ISSUE TITLE
Breaking Changes Introduced in Minor Version

### ISSUE THREAD

**Issue by remotelyliving** [alexdebril/rss-atom-bundle#132]
Hi, I know we're a few versions ahead already, but we thought it work raising an issue.

There was a breaking change in namespacing from v2.4.3 to v2.5

Someone on our team updated their composer file and we got 2.5 and an immediate 

`PHP Fatal error:  Class ‘Debril\\RssAtomBundle\\Protocol\\Formatter\\FeedRssFormatter’ not found in /var/www/...`

It's definitely worth a patch as it breaks and is unexpected behavior in light of semver.

**Comment by alexdebril** [comment]
Hi,

In the meantime you can force version 2.5.1 in your composer.json, this will fix the issue. As the version 2.5 is transitional, there should be no break. Instead, I accidentally merged a 3.0 branch into it and that's why you got this problem on v2.5.2. 

I'll fix this quickly, thank you for your feedback

**Comment by alexdebril** [comment]
fixed with v2.5.3
