### ISSUE TITLE
Bad class on phpdoc?

### ISSUE THREAD

**Issue by Soullivaneuh** [alexdebril/rss-atom-bundle#56]
Hi,

In the [wiki](https://github.com/alexdebril/rss-atom-bundle/wiki/Reading-feeds#using-getfeedcontent), it says:

```
Out of the box, getFeedContent() returns a FeedContent instance.
```

But, in your class, the phpDoc specify a `FeedIn` return tag.
See here: https://github.com/alexdebril/rss-atom-bundle/blob/master/Protocol/FeedReader.php#L114-L116

This generate error from my IDE but works like said on the wiki, is the phpDoc outdated?

Thanks.

**Comment by Soullivaneuh** [comment]
ping @alexdebril

**Comment by alexdebril** [comment]
Hi,

Take a look at this line : https://github.com/alexdebril/rss-atom-bundle/blob/master/Protocol/FeedReader.php#L139

FeedReader calls the factory to build a FeedInInterface instance (which is a FeedContent if you don't specify anything).

Then the factory creates a new object and checks if it's a FeedInInterface instance before returning it : https://github.com/alexdebril/rss-atom-bundle/blob/master/Protocol/Parser/Factory.php

So the wiki is a little bit outdated since it doesn't mention the ability to set the class in the factory settings.

Does that sound good to you ?

Alex

**Comment by Soullivaneuh** [comment]
I think I see the purpose.

In this case, I think you should specify both classes on `@return` php doc to make in working with IDE.

Or review inheritance system.
