### ISSUE TITLE
Impossible to guess date format: ah

### ISSUE THREAD

**Issue by AntonioAmore** [alexdebril/rss-atom-bundle#94]
Reading a feed get the mentioned above message.
I can add new dates formats to the bundle's configuration, but even can't understand where it takes **ah**, and what is it.

The feed content contains a line. May it be a source of the error?
```
<dc:creator>ah</dc:creator>
```
I can provide feed link, if needed.

**Comment by alexdebril** [comment]
Yes, give me the link to the feed please.

**Comment by AntonioAmore** [comment]
Here it is:  www.agrarheute.com/gefluegel.xml

**Comment by alexdebril** [comment]
Hi,

It's because the publication date is written in german, it's not a valid RSS or Atom date format, I can provide more explanations about it. Look at : https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.agrarheute.com%2Fnews.xml

Unless there's a growing need of supporting weird date formats, I won't fix this issue right now.

Sorry

**Comment by AntonioAmore** [comment]
Thank you!
